// chrome-xray OpenAPI 3.1 export: one-way projection of collated endpoints
// into a spec other tools can consume.

function toOpenAPISchema(schema) {
  if (!schema) return {};
  const type = String(schema.type || '');
  if (type.includes('|')) {
    return { oneOf: type.split('|').map((t) => ({ type: t === 'null' ? 'null' : t })) };
  }
  const out = { type: schema.type };
  if (schema.type === 'object' && schema.properties) {
    out.properties = {};
    for (const [k, v] of Object.entries(schema.properties)) {
      out.properties[k] = toOpenAPISchema(v);
    }
    const optional = new Set(schema.optional || []);
    const required = Object.keys(schema.properties).filter((k) => !optional.has(k));
    if (required.length) out.required = required;
  }
  if (schema.type === 'array' && schema.items) {
    out.items = toOpenAPISchema(schema.items);
  }
  return out;
}

function dominant(counts) {
  let best = null, n = -1;
  for (const [k, v] of Object.entries(counts || {})) {
    if (v > n) { best = k; n = v; }
  }
  return best;
}

export function toOpenAPI(profile, endpoints) {
  const servers = [...new Set(endpoints.map((e) => `${e.scheme}://${e.host}`))]
    .map((url) => ({ url }));

  const paths = {};
  for (const ep of endpoints) {
    const path = ep.template;
    paths[path] = paths[path] || {};
    const op = {
      summary: `${ep.method} ${ep.template}`,
      description: `Observed ${ep.count}× by chrome-xray. Avg ${ep.count ? Math.round(ep.totalMs / ep.count) : 0} ms.`,
      parameters: [],
      responses: {},
    };
    for (const p of ep.params || []) {
      op.parameters.push({ name: p, in: 'path', required: true, schema: { type: 'string' } });
    }
    for (const q of Object.keys(ep.queryKeys || {})) {
      op.parameters.push({ name: q, in: 'query', required: false, schema: { type: 'string' } });
    }
    if (!op.parameters.length) delete op.parameters;

    const reqCT = dominant(ep.reqContentTypes);
    if (ep.reqSchema && reqCT) {
      op.requestBody = { content: { [reqCT]: { schema: toOpenAPISchema(ep.reqSchema) } } };
    }

    const resCT = dominant(ep.resContentTypes) || 'application/json';
    for (const status of Object.keys(ep.statuses || {})) {
      if (status === 'error') continue;
      const r = { description: `Observed ${ep.statuses[status]}×` };
      if (ep.resSchema && Number(status) >= 200 && Number(status) < 300) {
        r.content = { [resCT]: { schema: toOpenAPISchema(ep.resSchema) } };
      }
      op.responses[status] = r;
    }
    if (!Object.keys(op.responses).length) {
      op.responses.default = { description: 'No completed responses observed' };
    }

    paths[path][ep.method.toLowerCase()] = op;
  }

  return {
    openapi: '3.1.0',
    info: {
      title: `${profile.name} — observed API`,
      version: new Date().toISOString().slice(0, 10),
      description: 'Generated by chrome-xray from live captured traffic. Schemas are inferred from observed payloads, not authoritative.',
    },
    servers,
    paths,
  };
}
