// chrome-xray OpenAPI: one-way export of collated endpoints, and import of
// served specs (OpenAPI 3.x / Swagger 2.0 JSON) into endpoint definitions.

import { endpointId } from './collate.js';

function toOpenAPISchema(schema) {
  if (!schema) return {};
  const type = String(schema.type || '');
  if (type.includes('|')) {
    return { oneOf: type.split('|').map((t) => ({ type: t === 'null' ? 'null' : t })) };
  }
  const out = { type: schema.type };
  if (schema.type === 'object' && schema.properties) {
    out.properties = {};
    for (const [k, v] of Object.entries(schema.properties)) {
      out.properties[k] = toOpenAPISchema(v);
    }
    const optional = new Set(schema.optional || []);
    const required = Object.keys(schema.properties).filter((k) => !optional.has(k));
    if (required.length) out.required = required;
  }
  if (schema.type === 'array' && schema.items) {
    out.items = toOpenAPISchema(schema.items);
  }
  return out;
}

function dominant(counts) {
  let best = null, n = -1;
  for (const [k, v] of Object.entries(counts || {})) {
    if (v > n) { best = k; n = v; }
  }
  return best;
}

export function toOpenAPI(profile, endpoints) {
  const servers = [...new Set(endpoints.map((e) => `${e.scheme}://${e.host}`))]
    .map((url) => ({ url }));

  const paths = {};
  for (const ep of endpoints) {
    const path = ep.template;
    paths[path] = paths[path] || {};
    const op = {
      summary: `${ep.method} ${ep.template}`,
      description: `Observed ${ep.count}× by chrome-xray. Avg ${ep.count ? Math.round(ep.totalMs / ep.count) : 0} ms.`,
      parameters: [],
      responses: {},
    };
    for (const p of ep.params || []) {
      op.parameters.push({ name: p, in: 'path', required: true, schema: { type: 'string' } });
    }
    for (const q of Object.keys(ep.queryKeys || {})) {
      op.parameters.push({ name: q, in: 'query', required: false, schema: { type: 'string' } });
    }
    if (!op.parameters.length) delete op.parameters;

    const reqCT = dominant(ep.reqContentTypes);
    if (ep.reqSchema && reqCT) {
      op.requestBody = { content: { [reqCT]: { schema: toOpenAPISchema(ep.reqSchema) } } };
    }

    const resCT = dominant(ep.resContentTypes) || 'application/json';
    for (const status of Object.keys(ep.statuses || {})) {
      if (status === 'error') continue;
      const r = { description: `Observed ${ep.statuses[status]}×` };
      if (ep.resSchema && Number(status) >= 200 && Number(status) < 300) {
        r.content = { [resCT]: { schema: toOpenAPISchema(ep.resSchema) } };
      }
      op.responses[status] = r;
    }
    if (!Object.keys(op.responses).length) {
      op.responses.default = { description: 'No completed responses observed' };
    }

    paths[path][ep.method.toLowerCase()] = op;
  }

  return {
    openapi: '3.1.0',
    info: {
      title: `${profile.name} — observed API`,
      version: new Date().toISOString().slice(0, 10),
      description: 'Generated by chrome-xray from live captured traffic. Schemas are inferred from observed payloads, not authoritative.',
    },
    servers,
    paths,
  };
}

// ---- spec import: OpenAPI 3.x / Swagger 2.0 -> endpoint records ----

function resolveRef(doc, ref) {
  if (typeof ref !== 'string' || !ref.startsWith('#/')) return null;
  let node = doc;
  for (const part of ref.slice(2).split('/')) {
    node = node && node[part.replace(/~1/g, '/').replace(/~0/g, '~')];
  }
  return node || null;
}

// Convert an OpenAPI schema into our lite schema shape.
function fromSpecSchema(s, doc, depth = 0, seen = new Set()) {
  if (!s || depth > 6) return null;
  if (s.$ref) {
    if (seen.has(s.$ref)) return { type: 'object' };
    const target = resolveRef(doc, s.$ref);
    return fromSpecSchema(target, doc, depth + 1, new Set([...seen, s.$ref]));
  }
  const variants = s.oneOf || s.anyOf || s.allOf;
  if (Array.isArray(variants) && variants.length) {
    return fromSpecSchema(variants[0], doc, depth + 1, seen);
  }
  if (s.type === 'object' || s.properties) {
    const properties = {};
    for (const [k, v] of Object.entries(s.properties || {})) {
      const c = fromSpecSchema(v, doc, depth + 1, seen);
      if (c) properties[k] = c;
    }
    const required = new Set(s.required || []);
    const optional = Object.keys(properties).filter((k) => !required.has(k));
    const out = { type: 'object', properties };
    if (optional.length) out.optional = optional;
    return out;
  }
  if (s.type === 'array') {
    return { type: 'array', items: fromSpecSchema(s.items, doc, depth + 1, seen) };
  }
  return { type: s.type || 'object' };
}

function specBase(doc, specUrl) {
  if (doc.swagger) { // v2
    const u = new URL(specUrl);
    const scheme = (doc.schemes && doc.schemes[0]) || u.protocol.replace(':', '');
    const host = doc.host || u.host;
    return new URL(`${scheme}://${host}${doc.basePath || ''}`);
  }
  const server = doc.servers && doc.servers[0] && doc.servers[0].url;
  // server URLs may be relative to where the spec is served
  return new URL(server || '/', specUrl);
}

function pick2xxResponse(op, doc) {
  for (const [code, res] of Object.entries(op.responses || {})) {
    if (!/^2/.test(code)) continue;
    const r = res && res.$ref ? resolveRef(doc, res.$ref) : res;
    if (!r) continue;
    if (r.schema) return { schema: r.schema, ct: 'application/json' }; // v2
    for (const [ct, media] of Object.entries(r.content || {})) {
      if (media && media.schema) return { schema: media.schema, ct: ct.split(';')[0] };
    }
  }
  return null;
}

function reqBodyOf(op, params, doc) {
  if (op.requestBody) { // v3
    const rb = op.requestBody.$ref ? resolveRef(doc, op.requestBody.$ref) : op.requestBody;
    for (const [ct, media] of Object.entries((rb && rb.content) || {})) {
      if (media && media.schema) return { schema: media.schema, ct: ct.split(';')[0] };
    }
  }
  const bodyParam = params.find((p) => p.in === 'body'); // v2
  if (bodyParam && bodyParam.schema) return { schema: bodyParam.schema, ct: 'application/json' };
  return null;
}

const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete', 'options', 'head'];

// Returns { endpoints, title } for a parsed spec document.
export function fromOpenAPI(doc, profileId, specUrl) {
  const base = specBase(doc, specUrl);
  const host = base.host;
  const scheme = base.protocol.replace(':', '');
  const prefix = base.pathname.replace(/\/$/, '');
  const now = Date.now();
  const endpoints = [];

  for (const [path, item] of Object.entries(doc.paths || {})) {
    if (!item) continue;
    const shared = Array.isArray(item.parameters) ? item.parameters : [];
    for (const m of HTTP_METHODS) {
      const op = item[m];
      if (!op) continue;
      const method = m.toUpperCase();
      const template = (prefix + path).replace(/\/{2,}/g, '/') || '/';
      const allParams = [...shared, ...(op.parameters || [])]
        .map((p) => (p && p.$ref ? resolveRef(doc, p.$ref) : p))
        .filter(Boolean);
      const params = [...(template.match(/\{([^}]+)\}/g) || [])].map((s) => s.slice(1, -1));
      const queryKeys = {};
      for (const p of allParams) if (p.in === 'query' && p.name) queryKeys[p.name] = 0;

      const req = reqBodyOf(op, allParams, doc);
      const res = pick2xxResponse(op, doc);

      endpoints.push({
        id: endpointId(profileId, method, host, template),
        profileId,
        method,
        host,
        scheme,
        template,
        params,
        queryKeys,
        statuses: {},
        count: 0,
        totalMs: 0,
        reqSchema: req ? fromSpecSchema(req.schema, doc) : null,
        resSchema: res ? fromSpecSchema(res.schema, doc) : null,
        reqContentTypes: req ? { [req.ct]: 0 } : {},
        resContentTypes: res ? { [res.ct]: 0 } : {},
        exampleIds: [],
        firstSeen: now,
        lastSeen: 0,
        source: 'spec',
        specUrl,
        summary: op.summary || op.description || undefined,
      });
    }
  }
  const title = (doc.info && doc.info.title) || specUrl;
  return { endpoints, title };
}
